# Generated by Django 4.1.3 on 2022-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userIMG',
            field=models.ImageField(default='default/default_profile.png', upload_to='users'),
        ),
    ]
