# Generated by Django 4.1.3 on 2022-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_userimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has2FA',
            field=models.BooleanField(default=False),
        ),
    ]
