# Generated by Django 4.1.3 on 2022-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('courseName', models.TextField(max_length=32)),
                ('shortDescription', models.TextField(default=models.TextField(max_length=32), max_length=80)),
                ('longDescription', models.TextField(default=models.TextField(default=models.TextField(max_length=32), max_length=80), max_length=2000)),
                ('likeRatio', models.IntegerField()),
            ],
            options={
                'ordering': ['courseID'],
            },
        ),
    ]
