# Generated by Django 4.1.3 on 2022-12-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('courseName', models.TextField(max_length=32)),
                ('shortDescription', models.TextField(default=models.TextField(max_length=32), max_length=80)),
                ('longDescription', models.TextField(default=models.TextField(default=models.TextField(max_length=32), max_length=80), max_length=2000)),
                ('courseIMG', models.URLField(default='https://cdn.discordapp.com/attachments/230245539520708608/1049264539629277194/image.png')),
                ('likeRatio', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['courseID'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(choices=[(-1, 'Undefined'), (0, 'Dislike'), (1, 'Like')])),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['courseID'],
            },
        ),
        migrations.CreateModel(
            name='CoursesVideos',
            fields=[
                ('videoID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('videoURL', models.URLField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'ordering': ['videoID'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('courseID', 'userID'), name='uniqueLike'),
        ),
    ]
