# Generated by Django 4.1.3 on 2022-11-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='likeRatio',
            field=models.IntegerField(default=-1),
        ),
    ]
