# Generated by Django 4.1.3 on 2022-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='like',
            field=models.IntegerField(choices=[(-1, 'Undefined'), (0, 'Dislike'), (1, 'Like')], default=-1),
        ),
    ]
