# Generated by Django 4.1.3 on 2022-12-12 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(choices=[(-1, 'Undefined'), (0, 'Dislike'), (1, 'Like')], default=-1)),
            ],
            options={
                'ordering': ['courseID'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='uniqueLike',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='like',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('courseID', 'userID'), name='uniqueSub'),
        ),
        migrations.AddField(
            model_name='like',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AddField(
            model_name='like',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('courseID', 'userID'), name='uniqueLike'),
        ),
    ]
