# Generated by Django 4.1.3 on 2022-12-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_subscription_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesvideos',
            options={'ordering': ['courseID']},
        ),
        migrations.AddField(
            model_name='coursesvideos',
            name='videoName',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
