# Generated by Django 4.1.3 on 2022-12-07 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursesvideos_options_coursesvideos_videoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
