# Generated by Django 4.1.3 on 2022-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_courseimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='likeRatio',
            field=models.IntegerField(default=0),
        ),
    ]
